/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorVenta;
import Modelo.Factura;
import Modelo.Producto;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Win 10
 */
public class FrmPagoTarjeta extends javax.swing.JFrame {

    ControladorVenta controllerVenta = new ControladorVenta();
    Factura nuevaFactura;
    DefaultTableModel model;
    JComboBox clientes;
    JTextField cantidad;
    JTable tblDetalles;
    float totalFactura;
    String medioDePago;

    public FrmPagoTarjeta(Factura f, float total, DefaultTableModel m, JComboBox c, JTextField cant, JTable d) {
        initComponents();
        nuevaFactura = f;
        model = m;
        clientes = c;
        cantidad = cant;
        tblDetalles = d;
        totalFactura = total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbtMercadoPago = new javax.swing.JRadioButton();
        rbtPosnet = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("TARJETA");

        buttonGroup1.add(rbtMercadoPago);
        rbtMercadoPago.setText("Mercado Pago");
        rbtMercadoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMercadoPagoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtPosnet);
        rbtPosnet.setText("Posnet");

        jLabel2.setText("Medio de Pago:");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(rbtPosnet, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtMercadoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rbtPosnet)
                    .addComponent(rbtMercadoPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        medioDePago = "";

        if (rbtMercadoPago.isSelected()) {
            medioDePago = "Mercado Pago";
        } else if (rbtPosnet.isSelected()) {
            medioDePago = "Posnet";
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar el medio de pago...");
            return;
        }

        nuevaFactura.setMedioDePago(medioDePago);

        try {
            if (controllerVenta.RegistrarFactura(nuevaFactura)) {
                JOptionPane.showMessageDialog(null, "Se ha registrado la venta");
                try {
                    generarFactura();
                } catch (DocumentException ex) {
                    Logger.getLogger(FrmPagoEfectivo.class.getName()).log(Level.SEVERE, null, ex);
                }
                model.setRowCount(0);
                clientes.setSelectedIndex(-1);
                cantidad.setText("");
                this.hide();
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbtMercadoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMercadoPagoActionPerformed
        // TODO add your handling code here:
        FrmMercadoPago frmMP=new FrmMercadoPago();
            frmMP.setVisible(true);
    }//GEN-LAST:event_rbtMercadoPagoActionPerformed

    private void generarFactura() throws DocumentException {

        String path = "/";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }

        Document doc = new Document();

        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path + "/factura.pdf"));
            doc.open();
            doc.add(new Paragraph("Fecha: " + nuevaFactura.getFecha(),
                    FontFactory.getFont("arial", 22)));
            PdfPTable tbl = new PdfPTable(4);
            tbl.addCell("Producto");
            tbl.addCell("Precio");
            tbl.addCell("Cantidad");
            tbl.addCell("Subtotal");
            tbl.setSpacingAfter(20);
            tbl.setSpacingBefore(10);
            for (int i = 0; i < tblDetalles.getRowCount(); i++) {
                Producto producto = (Producto) tblDetalles.getValueAt(i, 1);
                String descripcion = producto.getNombre();
                String precio = tblDetalles.getValueAt(i, 2).toString();
                String cantidad = tblDetalles.getValueAt(i, 3).toString();
                String subtotal = tblDetalles.getValueAt(i, 4).toString();

                tbl.addCell(descripcion);
                tbl.addCell(precio);
                tbl.addCell(cantidad);
                tbl.addCell(subtotal);
            }
            doc.add(tbl);
            doc.add(new Paragraph("Total a pagar: " + "$ " + totalFactura, FontFactory.getFont("arial", 30)));
            doc.add(new Paragraph("Medio de Pago: " + medioDePago, FontFactory.getFont("arial", 15)));

        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmPagoEfectivo.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rbtMercadoPago;
    private javax.swing.JRadioButton rbtPosnet;
    // End of variables declaration//GEN-END:variables
}
